from __future__ import annotations

import json
import os
import re
from datetime import datetime
from typing import Any, Dict, Iterable, List, Optional, Sequence

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from rag.generator import call_llm

OUTPUT_DIR = "generated_documents"
os.makedirs(OUTPUT_DIR, exist_ok=True)


# ─────────────────────────────────────────────────────────────────────────────
# Shared helpers
# ─────────────────────────────────────────────────────────────────────────────

def _safe_filename(text: str) -> str:
    text = text or "document"
    text = re.sub(r"[^\w\s.-]", "", str(text), flags=re.UNICODE)
    text = re.sub(r"\s+", "_", text.strip())
    return text[:80] or "document"


def _clean(text: object, default: str = "[Not provided]") -> str:
    if text is None:
        return default
    s = str(text).strip()
    return s if s else default


def _fmt_date(value: Optional[str]) -> str:
    return str(value) if value else "[DD-MM-YYYY]"


def _fmt_time(value: Optional[str]) -> str:
    return str(value) if value else "[HH:MM]"


def _p(value: object) -> str:
    """Escape for ReportLab Paragraph and convert newlines."""
    s = _clean(value)
    s = s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    s = s.replace("\n", "<br/>")
    return s


def _styles():
    styles = getSampleStyleSheet()

    styles.add(ParagraphStyle(
        name="DocTitleIndian",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=16, leading=20,
        alignment=TA_CENTER, spaceAfter=8,
        textColor=colors.HexColor("#143B5D"),
    ))
    styles.add(ParagraphStyle(
        name="DocSubTitleIndian",
        parent=styles["Normal"],
        fontName="Helvetica-Oblique",
        fontSize=9, leading=11,
        alignment=TA_CENTER, spaceAfter=8,
        textColor=colors.HexColor("#555555"),
    ))
    styles.add(ParagraphStyle(
        name="SectionHeadingIndian",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=11, leading=13,
        alignment=TA_LEFT,
        textColor=colors.HexColor("#143B5D"),
        spaceBefore=8, spaceAfter=4,
    ))
    styles.add(ParagraphStyle(
        name="BodyIndian",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10.2, leading=14,
        alignment=TA_LEFT, spaceAfter=4,
    ))
    styles.add(ParagraphStyle(
        name="BodyJustified",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10.2, leading=14,
        alignment=TA_JUSTIFY, spaceAfter=5,
    ))
    styles.add(ParagraphStyle(
        name="SmallIndian",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8.5, leading=10,
        alignment=TA_LEFT,
        textColor=colors.HexColor("#666666"),
    ))
    styles.add(ParagraphStyle(
        name="ClauseTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=10.2, leading=13,
        spaceAfter=2, spaceBefore=6,
        textColor=colors.HexColor("#1A3A5C"),
    ))
    return styles


def _page_footer(canvas, doc):
    canvas.saveState()
    width, _ = A4
    canvas.setStrokeColor(colors.HexColor("#C8C8C8"))
    canvas.setLineWidth(0.6)
    canvas.line(doc.leftMargin, 15 * mm, width - doc.rightMargin, 15 * mm)
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.HexColor("#666666"))
    canvas.drawString(doc.leftMargin, 10 * mm, "Generated by Legal AI Assistant")
    canvas.drawRightString(width - doc.rightMargin, 10 * mm, f"Page {canvas.getPageNumber()}")
    canvas.restoreState()


def _kv_table(rows: Sequence[Sequence[object]], styles, col_widths=(55 * mm, 115 * mm)):
    data = []
    for key, value in rows:
        data.append([
            Paragraph(f"<b>{_p(key)}</b>", styles["BodyIndian"]),
            Paragraph(_p(value), styles["BodyIndian"]),
        ])
    table = Table(data, colWidths=list(col_widths), hAlign="LEFT")
    table.setStyle(TableStyle([
        ("BACKGROUND",   (0, 0), (0, -1), colors.HexColor("#DCE8F3")),
        ("BACKGROUND",   (1, 0), (1, -1), colors.white),
        ("BOX",          (0, 0), (-1, -1), 0.6, colors.HexColor("#A8C0D8")),
        ("INNERGRID",    (0, 0), (-1, -1), 0.4, colors.HexColor("#A8C0D8")),
        ("VALIGN",       (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING",   (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 5),
        ("LEFTPADDING",  (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ]))
    return table


def _section(title: str, styles):
    return [
        Paragraph(title.upper(), styles["SectionHeadingIndian"]),
        HRFlowable(width="100%", thickness=0.7, color=colors.HexColor("#2C5F8A"),
                   spaceBefore=0, spaceAfter=4),
    ]


def _clause(number: int, title: str, body: str, styles):
    """Numbered clause with bold title, used in agreements."""
    return [
        Paragraph(f"<b>Clause {number}. {title}</b>", styles["ClauseTitle"]),
        Paragraph(_p(body), styles["BodyJustified"]),
        Spacer(1, 3),
    ]


def _bullets(items: Iterable[str], styles, numbered: bool = True):
    out = []
    for idx, item in enumerate(items, start=1):
        prefix = f"{idx}. " if numbered else "• "
        out.append(Paragraph(_p(prefix + item), styles["BodyIndian"]))
    return out


def _build_pdf(filename: str, story):
    filepath = os.path.join(OUTPUT_DIR, filename)
    doc = SimpleDocTemplate(
        filepath, pagesize=A4,
        leftMargin=18 * mm, rightMargin=18 * mm,
        topMargin=16 * mm, bottomMargin=18 * mm,
        title=filename, author="Legal AI Assistant",
    )
    doc.build(story, onFirstPage=_page_footer, onLaterPages=_page_footer)
    return filename


def _llm_json(prompt: str, mode: str = "auto") -> Dict[str, Any]:
    raw = call_llm(prompt, mode=mode)
    raw = re.sub(r"```json|```", "", raw).strip()
    match = re.search(r"\{.*\}", raw, re.DOTALL)
    if match:
        raw = match.group()
    try:
        return json.loads(raw)
    except Exception:
        def _find(key: str, default: str = "") -> str:
            m = re.search(rf'"{re.escape(key)}"\s*:\s*"(.*?)"', raw, re.DOTALL)
            return m.group(1).replace("\\n", "\n") if m else default
        # Return a best-effort dict with all known keys
        return {k: _find(k) for k in [
            "complainant_name", "complainant_address", "father_name", "address",
            "respondent_name", "respondent_address", "location", "issue",
            "incident_date", "incident_time", "incident_details",
            "police_station", "district", "state", "demand", "reply_days",
            "relationship", "incident_dates", "demand_amount", "additional_details",
            "custom_terms", "landlord_name", "landlord_address", "tenant_name",
            "tenant_address", "house_no", "property_address", "rent_amount",
            "security_deposit", "start_date", "end_date", "notice_period",
            "lock_in_period", "maintenance", "utilities", "name", "age",
            "occupation", "id_proof", "purpose", "custom_facts",
            "smart_reply", "detected_intent",
        ]}


# ─────────────────────────────────────────────────────────────────────────────
# IPC detection + risk (deterministic, no RAG)
# ─────────────────────────────────────────────────────────────────────────────

def detect_ipc_sections(text: str) -> List[str]:
    text = (text or "").lower()
    ipc_map = {
        "theft":                    ["IPC 379 - Theft"],
        "stolen":                   ["IPC 379 - Theft"],
        "robbery":                  ["IPC 392 - Robbery"],
        "dacoity":                  ["IPC 395 - Dacoity"],
        "fraud":                    ["IPC 420 - Cheating and dishonestly inducing delivery of property"],
        "cheat":                    ["IPC 420 - Cheating"],
        "cheating":                 ["IPC 420 - Cheating"],
        "assault":                  ["IPC 351 - Assault", "IPC 323 - Punishment for voluntarily causing hurt"],
        "hurt":                     ["IPC 319 - Hurt", "IPC 323 - Voluntarily causing hurt"],
        "grievous hurt":            ["IPC 320 - Grievous hurt", "IPC 325 - Punishment for grievous hurt"],
        "beaten":                   ["IPC 323 - Voluntarily causing hurt", "IPC 351 - Assault"],
        "beat":                     ["IPC 323 - Voluntarily causing hurt"],
        "attacked":                 ["IPC 351 - Assault", "IPC 323 - Voluntarily causing hurt"],
        "threat":                   ["IPC 506 - Criminal intimidation"],
        "threaten":                 ["IPC 506 - Criminal intimidation"],
        "harassment":               ["IPC 354 - Assault or criminal force on woman", "IPC 498A - Cruelty by husband"],
        "stalking":                 ["IPC 354D - Stalking"],
        "rape":                     ["IPC 376 - Punishment for rape"],
        "sexual assault":           ["IPC 376 - Punishment for rape", "IPC 354 - Assault or criminal force on woman"],
        "murder":                   ["IPC 302 - Punishment for murder"],
        "attempt to murder":        ["IPC 307 - Attempt to murder"],
        "kidnap":                   ["IPC 363 - Punishment for kidnapping"],
        "abduction":                ["IPC 362 - Abduction"],
        "breach of trust":          ["IPC 406 - Criminal breach of trust"],
        "criminal breach of trust": ["IPC 406 - Criminal breach of trust"],
        "extortion":                ["IPC 383 - Extortion", "IPC 384 - Punishment for extortion"],
        "blackmail":                ["IPC 383 - Extortion"],
        "criminal intimidation":    ["IPC 506 - Criminal intimidation"],
        "misappropriation":         ["IPC 403 - Dishonest misappropriation of property"],
        "trespass":                 ["IPC 441 - Criminal trespass", "IPC 447 - Punishment for criminal trespass"],
        "mischief":                 ["IPC 425 - Mischief", "IPC 427 - Punishment for mischief"],
        "defamation":               ["IPC 499 - Defamation", "IPC 500 - Punishment for defamation"],
        "forgery":                  ["IPC 463 - Forgery", "IPC 465 - Punishment for forgery"],
        "riot":                     ["IPC 146 - Rioting", "IPC 147 - Punishment for rioting"],
        "bribery":                  ["IPC 171B - Bribery"],
        "dowry":                    ["IPC 498A - Cruelty by husband or relatives", "Dowry Prohibition Act"],
        "eve teasing":              ["IPC 354 - Assault or criminal force on woman",
                                     "IPC 509 - Word, gesture or act intended to insult modesty"],
    }
    detected = {}
    for keyword, sections in ipc_map.items():
        if keyword in text:
            for sec in sections:
                detected[sec] = True
    return sorted(detected.keys())


def get_risk_level(issue: str) -> str:
    text = (issue or "").lower()
    if any(k in text for k in ["murder", "rape", "kidnap", "kidnapping", "attempt to murder", "sexual assault"]):
        return "🔴 High Risk — Immediate police action required"
    if any(k in text for k in ["fraud", "theft", "stolen", "assault", "hurt", "beaten",
                                "beat", "attacked", "extortion", "harassment", "blackmail"]):
        return "🟡 Medium Risk — Police complaint strongly recommended"
    return "🟢 Low Risk — Formal complaint advised"


def generate_legal_analysis(issue: str, ipc_sections: Optional[Sequence[str]] = None) -> str:
    text = (issue or "").lower()
    ipc_sections = list(ipc_sections or [])
    if any(k in text for k in ["beaten", "beat", "assault", "attacked", "hurt"]):
        return (
            "The facts indicate a physical assault / hurt complaint. "
            "IPC 323 applies to voluntarily causing hurt; IPC 325 applies if the injury is grievous. "
            "IPC 351 covers assault (threat of force). If the accused were in a group, Section 34 (common intention) "
            "or Section 149 (unlawful assembly) may also apply. "
            "Medical examination of the victim should be done immediately to document injuries."
        )
    if any(k in text for k in ["theft", "stolen"]):
        return "The facts indicate a property-offence complaint. IPC 379 applies if the ingredients of dishonest taking of movable property are made out."
    if any(k in text for k in ["fraud", "cheat", "cheating"]):
        return "The facts indicate a cheating/fraud complaint. If dishonest inducement and wrongful loss are shown, IPC 420 applies."
    if "threat" in text or "threaten" in text:
        return "The facts indicate criminal intimidation. If a threat to person, reputation, or property is present, IPC 506 applies."
    if ipc_sections:
        return (
            f"The complaint appears to involve: {', '.join(ipc_sections)}. "
            "Final legal classification depends on the exact facts, witnesses, and supporting evidence."
        )
    return "More details are needed to determine the exact legal sections applicable."


def generate_next_steps(issue: str, police_station: Optional[str] = None) -> List[str]:
    steps = [
        "Carry a printed copy of the complaint along with any photos, videos, medical papers, screenshots, or other proof.",
        f"Submit the complaint at {police_station or 'the nearest police station'} and request an acknowledgement / GD entry number.",
        "Ask for the FIR to be registered if the facts disclose a cognizable offence.",
        "Keep a signed copy or receipt for follow-up.",
        "If the complaint is not accepted, approach the SHO / ACP / SP with the same written complaint and proof of submission.",
    ]
    text = (issue or "").lower()
    if any(k in text for k in ["beaten", "beat", "assault", "attacked", "hurt"]):
        steps.insert(0, "Get a medical examination done IMMEDIATELY and obtain a medico-legal certificate (MLC) from the hospital.")
    return steps


# ─────────────────────────────────────────────────────────────────────────────
# Intelligent chat extraction (LLM)
# ─────────────────────────────────────────────────────────────────────────────

def extract_document_data_from_chat(
    chat_text: str,
    document_type: str,
    existing_draft: Dict[str, Any] = None,
    mode: str = "auto",
) -> Dict[str, Any]:
    document_type = (document_type or "").lower().strip()
    existing_draft_str = json.dumps(existing_draft or {}, indent=2)

    field_descriptions = {
        "fir": """
Extract for FIR:
- complainant_name: Full name of the person filing (NOT the accused)
- father_name: Father's name of the complainant
- address: Complainant's home address
- respondent_name: Name(s) of the accused
- location: Place of incident
- incident_date: Date of incident (DD-MM-YYYY)
- incident_time: Time of incident
- incident_details: Full description of what happened
- police_station: Police station name (if mentioned)
- district, state: Jurisdiction details
- witnesses: List of witness names
""",
        "notice": """
Extract for Legal Notice:
- complainant_name: Sender's full name
- complainant_address: Sender's complete address
- respondent_name: Recipient's full name
- respondent_address: Recipient's complete address
- issue: Main grievance
- demand: Specific demand (what the sender wants)
- reply_days: Days to respond (default 15)
- relationship: Sender's relationship with recipient
- incident_dates: Relevant dates of events
- demand_amount: Any monetary amount involved
- additional_details: Extra facts or context
- custom_terms: Any extra demands / terms the user wants to add
""",
        "rental": """
Extract for Rental Agreement:
- landlord_name, landlord_address: Landlord details
- tenant_name, tenant_address: Tenant details
- house_no: House/flat/unit number
- property_address: Complete address of the property
- rent_amount: Monthly rent (₹)
- security_deposit: Security deposit amount (₹)
- start_date, end_date: Lease period
- notice_period: Termination notice period (e.g., 1 month)
- lock_in_period: Minimum lock-in period before termination (e.g., 6 months)
- maintenance: Who pays maintenance / society charges
- utilities: Who pays electricity, water, gas
- additional_details: Other facts
- custom_terms: Any special/extra clauses the user wants included
""",
        "affidavit": """
Extract for Affidavit:
- name: Full name of deponent
- age: Deponent's age
- occupation: Deponent's occupation
- address: Complete residential address
- id_proof: ID proof type (Aadhaar / PAN / Voter ID / Passport)
- issue: Subject matter of affidavit
- additional_details: Facts and circumstances
- purpose: Where affidavit will be used
- custom_facts: Any extra statements the user wants to include
""",
    }.get(document_type, "Extract any relevant legal details.")

    prompt = f"""You are an expert Indian legal assistant helping a citizen fill a {document_type.upper()} document.

Your job:
1. Read the entire conversation carefully.
2. Extract ALL relevant information from the user's messages.
3. Understand natural language, Hinglish, indirect answers, yes/no confirmations.
4. NEVER lose previously collected data — always merge with existing_draft.
5. If the user answers "yes" to a question, understand what they agreed to.
6. Generate one smart, empathetic, natural conversational reply asking for the NEXT single missing piece.
7. If user provides custom_terms or custom_facts (additional clauses / facts), capture them verbatim.

{field_descriptions}

EXISTING DRAFT (do NOT lose this data):
{existing_draft_str}

CONVERSATION:
{chat_text}

RULES:
- Ask for ONE missing field at a time in smart_reply.
- Be empathetic — users may be in distress (assault, fraud cases).
- For rental/notice/affidavit: after collecting all required fields, ask: "Do you want to add any additional or special terms/clauses?" — if yes, collect and set custom_terms/custom_facts.
- Set ready_to_generate=true only when all required fields are filled.
- Return ONLY valid JSON, no markdown, no explanation.

Return JSON with ALL keys below (use "" for unknown string fields, [] for lists, false for booleans):
{{
  "complainant_name": "",
  "complainant_address": "",
  "father_name": "",
  "address": "",
  "respondent_name": "",
  "respondent_address": "",
  "location": "",
  "issue": "",
  "incident_date": "",
  "incident_time": "",
  "incident_details": "",
  "police_station": "",
  "district": "",
  "state": "",
  "demand": "",
  "reply_days": "",
  "relationship": "",
  "incident_dates": "",
  "demand_amount": "",
  "additional_details": "",
  "custom_terms": "",
  "landlord_name": "",
  "landlord_address": "",
  "tenant_name": "",
  "tenant_address": "",
  "house_no": "",
  "property_address": "",
  "rent_amount": "",
  "security_deposit": "",
  "start_date": "",
  "end_date": "",
  "notice_period": "",
  "lock_in_period": "",
  "maintenance": "",
  "utilities": "",
  "name": "",
  "age": "",
  "occupation": "",
  "id_proof": "",
  "purpose": "",
  "custom_facts": "",
  "witnesses": [],
  "annexures": [],
  "fir_number": "",
  "smart_reply": "Your empathetic, intelligent conversational response here",
  "detected_intent": "provide_info | asking_question | confirming | greeting | other",
  "ready_to_generate": false
}}"""

    data = _llm_json(prompt, mode=mode)

    merged = dict(existing_draft or {})
    for k, v in data.items():
        if k in ("smart_reply", "detected_intent", "ready_to_generate"):
            continue
        if v is not None and str(v).strip() not in ("", "[]", "null", "None"):
            if isinstance(v, list) and len(v) == 0:
                continue
            merged[k] = v

    merged["_smart_reply"]        = data.get("smart_reply", "")
    merged["_detected_intent"]    = data.get("detected_intent", "provide_info")
    merged["_ready_to_generate"]  = data.get("ready_to_generate", False)

    # FIR normalisations
    if document_type == "fir":
        if not merged.get("complainant_name") and merged.get("name"):
            merged["complainant_name"] = merged["name"]
        if not merged.get("incident_details") and merged.get("issue"):
            merged["incident_details"] = merged["issue"]
        if not merged.get("state"):
            merged["state"] = "Uttar Pradesh"

    return merged


# ─────────────────────────────────────────────────────────────────────────────
# FIR — unchanged from original (only added missing import guard)
# ─────────────────────────────────────────────────────────────────────────────

def generate_fir_document(
    name, issue, location, complainant_name,
    respondent_name=None, police_station=None, district=None,
    state="Uttar Pradesh", incident_date=None, incident_time=None,
    incident_details=None, witnesses=None, annexures=None,
    fir_number=None, language_note=None,
):
    styles = _styles()
    ipc_sections = detect_ipc_sections(incident_details or issue or "")
    risk         = get_risk_level(incident_details or issue or "")
    analysis     = generate_legal_analysis(incident_details or issue or "", ipc_sections)
    next_steps   = generate_next_steps(incident_details or issue or "", police_station=police_station)

    filename = f"FIR_{_safe_filename(complainant_name)}_{datetime.now().strftime('%d%m%Y_%H%M%S')}.pdf"
    story = []

    story += [Paragraph("उत्तर प्रदेश पुलिस", styles["DocTitleIndian"])]
    story += [Paragraph("FIRST INFORMATION REPORT (FIR)", styles["SectionHeadingIndian"])]
    story += [Paragraph("Draft complaint for police submission under Section 173 BNSS", styles["SmallIndian"])]
    story += [Paragraph("This is a draft. Final FIR registration is done by the police authority.", styles["SmallIndian"])]
    if language_note:
        story += [Paragraph(_p(language_note), styles["SmallIndian"])]
    story += [Spacer(1, 4)]

    story += _section("Office Use / Filing Details", styles)
    story.append(_kv_table([
        ("FIR No.",             fir_number or "[To be assigned by police]"),
        ("GD Entry No.",        "[To be filled by police]"),
        ("Police Station",      police_station or "[Police Station]"),
        ("District",            district or "[District]"),
        ("State / UT",          state or "[State / UT]"),
        ("Date of Information", datetime.now().strftime("%d-%m-%Y")),
        ("Time of Information", datetime.now().strftime("%H:%M")),
    ], styles))
    story.append(Spacer(1, 5))

    story += _section("Informant / Complainant Details", styles)
    story.append(_kv_table([
        ("Full Name",              complainant_name),
        ("Father / Husband Name",  name or "[Not provided]"),
        ("Address",                location),
        ("Contact Number",         "[Not provided]"),
        ("ID Proof",               "[Aadhaar / PAN / Voter ID]"),
    ], styles))
    story.append(Spacer(1, 5))

    story += _section("Accused / Opposite Party Details", styles)
    story.append(_kv_table([
        ("Name",              respondent_name or "[Unknown / Not known]"),
        ("Address",           "[If known]"),
        ("Other Identifiers", "[If known: phone, vehicle number, photo, description]"),
    ], styles))
    story.append(Spacer(1, 5))

    story += _section("Occurrence Details", styles)
    story.append(_kv_table([
        ("Date of Occurrence",         _fmt_date(incident_date)),
        ("Time of Occurrence",         _fmt_time(incident_time)),
        ("Place of Occurrence",        location),
        ("Nature of Offence / Incident", issue or incident_details or "[Not provided]"),
    ], styles))
    story.append(Spacer(1, 5))

    story += _section("Applicable Legal Sections", styles)
    story.append(Paragraph(
        f"{', '.join(ipc_sections) if ipc_sections else 'To be determined by investigating officer'}",
        styles["BodyIndian"]
    ))
    story.append(Spacer(1, 5))

    story += _section("Legal Analysis", styles)
    story.append(Paragraph(_p(analysis), styles["BodyJustified"]))
    story.append(Spacer(1, 5))

    story += _section("Risk Assessment", styles)
    story.append(Paragraph(_p(risk), styles["BodyIndian"]))
    story.append(Spacer(1, 5))

    story += _section("Facts of the Case", styles)
    facts = incident_details or (
        "I am submitting this information regarding the above incident. "
        "The facts are stated chronologically and truthfully to the best of my knowledge."
    )
    story.append(Paragraph(_p(facts), styles["BodyJustified"]))
    story.append(Spacer(1, 4))

    story += _section("Witnesses", styles)
    if witnesses:
        story += _bullets([_clean(w) for w in witnesses], styles)
    else:
        story.append(Paragraph("[Names, addresses, and phone numbers of witnesses, if any]", styles["BodyIndian"]))
    story.append(Spacer(1, 4))

    story += _section("Annexures / Supporting Documents", styles)
    if annexures:
        story += _bullets([_clean(a) for a in annexures], styles)
    else:
        story.append(Paragraph("[CCTV images, chat screenshots, call records, photos, medical papers, receipts, etc.]", styles["BodyIndian"]))
    story.append(Spacer(1, 4))

    story += _section("Next Steps", styles)
    for step in next_steps:
        story.append(Paragraph(f"• {step}", styles["BodyIndian"]))
    story.append(Spacer(1, 4))

    story += _section("Request / Relief Sought", styles)
    story.append(Paragraph(
        "I request that this information be registered and that appropriate police action be taken in accordance with law. "
        "A copy of the FIR / acknowledgement may be provided to me as per applicable procedure.",
        styles["BodyJustified"]
    ))
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        "Note: If this complaint is filed outside the correct jurisdiction, it may be treated as a Zero FIR "
        "and transferred to the appropriate police station.",
        styles["SmallIndian"]
    ))
    story.append(Spacer(1, 8))

    story.append(Table(
        [
            [Paragraph("<b>Signature / Thumb Impression of Informant</b>", styles["BodyIndian"]),
             Paragraph("__________________________", styles["BodyIndian"])],
            [Paragraph("<b>Name</b>",  styles["BodyIndian"]), Paragraph(_clean(complainant_name), styles["BodyIndian"])],
            [Paragraph("<b>Date</b>",  styles["BodyIndian"]), Paragraph(datetime.now().strftime("%d-%m-%Y"), styles["BodyIndian"])],
            [Paragraph("<b>Place</b>", styles["BodyIndian"]), Paragraph(_clean(location), styles["BodyIndian"])],
        ],
        colWidths=[70 * mm, 100 * mm], hAlign="LEFT"
    ))
    story[-1].setStyle(TableStyle([
        ("BOX",          (0, 0), (-1, -1), 0.5, colors.HexColor("#BBBBBB")),
        ("INNERGRID",    (0, 0), (-1, -1), 0.4, colors.HexColor("#DDDDDD")),
        ("BACKGROUND",   (0, 0), (0, -1), colors.HexColor("#F5F8FB")),
        ("VALIGN",       (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING",   (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 5),
        ("LEFTPADDING",  (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ]))

    story.append(Spacer(1, 6))
    story.append(Paragraph("Officer acknowledgment: ________________________________", styles["BodyIndian"]))
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        "Note: Jurisdictional details and final police headings may vary by State / UT and police station.",
        styles["SmallIndian"]
    ))

    return _build_pdf(filename, story)


# ─────────────────────────────────────────────────────────────────────────────
# Legal Notice — richer version
# ─────────────────────────────────────────────────────────────────────────────

def generate_legal_notice_document(
    complainant_name: str,
    complainant_address: str,
    respondent_name: str,
    respondent_address: str,
    issue: str,
    demand: str,
    reply_days: int = 15,
    relationship: str = "",
    incident_dates: str = "",
    demand_amount: str = "",
    additional_details: str = "",
    custom_terms: str = "",
    # Legacy compat
    name: str = "",
    location: str = "",
):
    # Legacy fallback
    complainant_name    = complainant_name or name
    complainant_address = complainant_address or location

    styles   = _styles()
    today    = datetime.now().strftime("%d-%m-%Y")
    filename = f"LegalNotice_{_safe_filename(complainant_name)}_{datetime.now().strftime('%d%m%Y_%H%M%S')}.pdf"

    story = [
        Paragraph("LEGAL NOTICE", styles["DocTitleIndian"]),
        Paragraph(
            "Issued under the Indian Contract Act, 1872 and applicable law — Draft for advocate review before service",
            styles["DocSubTitleIndian"]
        ),
        Spacer(1, 6),
    ]

    # Header block: sender + recipient side-by-side
    header_data = [
        [
            Paragraph("<b>FROM (Sender / Noticee)</b>", styles["BodyIndian"]),
            Paragraph("<b>TO (Recipient / Noticee)</b>", styles["BodyIndian"]),
        ],
        [
            Paragraph(_p(complainant_name), styles["BodyIndian"]),
            Paragraph(_p(respondent_name or "[Recipient Name]"), styles["BodyIndian"]),
        ],
        [
            Paragraph(_p(complainant_address), styles["BodyIndian"]),
            Paragraph(_p(respondent_address or "[Recipient Address]"), styles["BodyIndian"]),
        ],
    ]
    header_table = Table(header_data, colWidths=[88 * mm, 88 * mm], hAlign="LEFT")
    header_table.setStyle(TableStyle([
        ("BACKGROUND",   (0, 0), (-1, 0), colors.HexColor("#DCE8F3")),
        ("BOX",          (0, 0), (-1, -1), 0.6, colors.HexColor("#A8C0D8")),
        ("INNERGRID",    (0, 0), (-1, -1), 0.4, colors.HexColor("#A8C0D8")),
        ("VALIGN",       (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING",   (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 5),
        ("LEFTPADDING",  (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(header_table)
    story.append(Spacer(1, 5))

    story += _section("Notice Details", styles)
    story.append(_kv_table([
        ("Date of Notice",         today),
        ("Subject",                f"Legal Notice regarding: {issue}"),
        ("Relationship",           relationship or "[e.g. Employer / Tenant / Customer]"),
        ("Relevant Date(s)",       incident_dates or "[Dates of relevant events]"),
        ("Amount in Dispute",      demand_amount or "[If applicable]"),
        ("Response Period",        f"{reply_days} days from receipt of this notice"),
    ], styles))
    story.append(Spacer(1, 5))

    story += _section("Body of Notice", styles)

    notice_paras = [
        f"Under instructions from and on behalf of my client, <b>{_p(complainant_name)}</b>, "
        f"residing/having office at <b>{_p(complainant_address)}</b>, I hereby issue this legal "
        f"notice to you, <b>{_p(respondent_name or '[Recipient]')}</b>, at "
        f"<b>{_p(respondent_address or '[Recipient Address]')}</b>.",

        f"<b>Background and Facts:</b> {_p(issue)}",

        _p(additional_details) if additional_details else
        "[Provide a detailed chronological account of facts, dates, and relevant documents here.]",

        f"<b>Legal Basis:</b> Your actions as described above are in violation of your legal obligations "
        f"arising under the relevant provisions of law including but not limited to the Indian Contract Act, "
        f"1872, and such other applicable statutes as may be relevant to the facts herein.",

        f"<b>Demand:</b> You are hereby called upon to: {_p(demand or '[State specific demand]')}",

        f"You are required to comply with the above demand and send a written reply to this notice "
        f"within <b>{reply_days} ({"fifteen" if reply_days == 15 else reply_days}) days</b> from the date of "
        f"receipt of this notice.",

        "Failing compliance within the stipulated period, my client shall be constrained to initiate "
        "appropriate legal/civil/criminal proceedings against you before the competent court/authority, "
        "entirely at your risk as to costs and consequences, without any further notice.",

        "This notice is issued without prejudice to all other rights and remedies available to my client "
        "in law and equity, all of which are expressly reserved.",
    ]

    for para in notice_paras:
        story.append(Paragraph(para, styles["BodyJustified"]))
        story.append(Spacer(1, 3))

    # Custom terms / additional demands
    if custom_terms and str(custom_terms).strip().lower() not in ("no", "none", ""):
        story += _section("Additional Terms / Demands", styles)
        story.append(Paragraph(_p(custom_terms), styles["BodyJustified"]))
        story.append(Spacer(1, 4))

    story.append(Spacer(1, 8))
    story.append(Paragraph(f"Issued at: {complainant_address}", styles["BodyIndian"]))
    story.append(Paragraph(f"Date: {today}", styles["BodyIndian"]))
    story.append(Spacer(1, 8))
    story.append(Paragraph(f"Yours faithfully,<br/><br/><b>{_p(complainant_name)}</b>", styles["BodyIndian"]))
    story.append(Spacer(1, 8))
    story.append(Paragraph("Signature: ___________________________", styles["BodyIndian"]))
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        "Note: This draft notice should be reviewed and served by an advocate on stamp paper for full legal effect.",
        styles["SmallIndian"]
    ))

    return _build_pdf(filename, story)


# ─────────────────────────────────────────────────────────────────────────────
# Rental Agreement — richer version
# ─────────────────────────────────────────────────────────────────────────────

def generate_rental_agreement_document(
    landlord_name: str,
    landlord_address: str,
    tenant_name: str,
    tenant_address: str,
    house_no: str,
    property_address: str,
    rent_amount: str,
    security_deposit: str,
    start_date: str,
    end_date: str,
    notice_period: str = "1 month",
    lock_in_period: str = "",
    maintenance: str = "",
    utilities: str = "",
    additional_details: str = "",
    custom_terms: str = "",
    # Legacy compat
    name: str = "",
    location: str = "",
):
    landlord_name    = landlord_name or name
    property_address = property_address or location

    styles   = _styles()
    today    = datetime.now().strftime("%d-%m-%Y")
    filename = f"RentalAgreement_{_safe_filename(landlord_name)}_{datetime.now().strftime('%d%m%Y_%H%M%S')}.pdf"

    story = [
        Paragraph("RENTAL AGREEMENT", styles["DocTitleIndian"]),
        Paragraph(
            "Leave and License Agreement under the Transfer of Property Act, 1882 — "
            "Draft for stamp duty registration and legal review",
            styles["DocSubTitleIndian"]
        ),
        Spacer(1, 6),
    ]

    # ── Parties ──────────────────────────────────────────────────────────────
    story += _section("1. Parties to the Agreement", styles)
    story.append(_kv_table([
        ("Agreement Date",      today),
        ("Landlord / Licensor", landlord_name),
        ("Landlord Address",    landlord_address or "[Landlord permanent address]"),
        ("Tenant / Licensee",   tenant_name),
        ("Tenant Address",      tenant_address or "[Tenant permanent address]"),
    ], styles))
    story.append(Spacer(1, 5))

    # ── Property ─────────────────────────────────────────────────────────────
    story += _section("2. Property Details", styles)
    story.append(_kv_table([
        ("House / Flat / Unit No.",  house_no or "[Flat/House No.]"),
        ("Property Address",         property_address),
        ("Property Type",            "[Apartment / Independent House / Commercial / Other]"),
        ("Floor",                    "[Floor Number if applicable]"),
        ("Furnished Status",         "[Fully Furnished / Semi-Furnished / Unfurnished]"),
    ], styles))
    story.append(Spacer(1, 5))

    # ── Financial ────────────────────────────────────────────────────────────
    story += _section("3. Financial Terms", styles)
    story.append(_kv_table([
        ("Monthly Rent (₹)",          rent_amount or "[Amount]"),
        ("Security / Refundable Deposit (₹)", security_deposit or "[Amount]"),
        ("Rent Due Date",             "On or before the 5th of each calendar month"),
        ("Late Payment Penalty",      "As mutually agreed / [Amount] per day after grace period"),
        ("Payment Method",            "[Cash / Bank Transfer / UPI — as agreed]"),
        ("Maintenance / Society Charges", maintenance or "[Landlord / Tenant — as agreed]"),
        ("Utilities (Electricity / Water / Gas)", utilities or "[Tenant's responsibility unless stated otherwise]"),
    ], styles))
    story.append(Spacer(1, 5))

    # ── Tenure ───────────────────────────────────────────────────────────────
    story += _section("4. Tenure and Renewal", styles)
    story.append(_kv_table([
        ("Lease Start Date",    _fmt_date(start_date)),
        ("Lease End Date",      _fmt_date(end_date)),
        ("Lock-In Period",      lock_in_period if lock_in_period and str(lock_in_period).lower() not in ("no", "none", "") else "None"),
        ("Notice Period",       f"{notice_period} written notice required by either party to terminate"),
        ("Renewal",             "By mutual written agreement before the expiry of this agreement"),
        ("Rent Escalation",     "[e.g. 5–10% per year on renewal — as mutually agreed]"),
    ], styles))
    story.append(Spacer(1, 5))

    # ── Standard Clauses ─────────────────────────────────────────────────────
    story += _section("5. Obligations and Standard Clauses", styles)

    clauses = [
        ("Rent Payment",
         f"The Tenant shall pay a monthly rent of ₹{rent_amount or '[Amount]'} on or before the 5th of each month. "
         f"A security deposit of ₹{security_deposit or '[Amount]'} has been paid by the Tenant and shall be refunded "
         "within 30 days of vacating the premises after deduction of legitimate dues and damages, if any."),

        ("Use of Premises",
         "The Tenant shall use the premises solely for residential / agreed purposes and shall not use the premises "
         "for any illegal, immoral, or nuisance activity. The Tenant shall not make structural alterations, additions, "
         "or modifications without prior written consent of the Landlord."),

        ("Subletting",
         "The Tenant shall not sublet, assign, or transfer the premises or any part thereof without the prior written "
         "consent of the Landlord."),

        ("Maintenance and Repairs",
         f"Routine maintenance and day-to-day upkeep of the premises shall be the responsibility of the Tenant. "
         f"Major structural repairs shall be the responsibility of the Landlord. "
         f"Maintenance / society charges: {maintenance or '[as agreed between parties]'}. "
         f"Utilities (electricity, water, gas): {utilities or 'to be borne by the Tenant unless otherwise agreed'}."),

        ("Inspection",
         "The Landlord or his authorized representative shall have the right to inspect the premises at a reasonable "
         "time with prior notice of at least 24 hours to the Tenant."),

        ("Termination",
         f"Either party may terminate this agreement by giving {notice_period or 'one month'} written notice. "
         + (f"During the lock-in period of {lock_in_period}, neither party may terminate except for material breach. "
            if lock_in_period and str(lock_in_period).lower() not in ("no", "none", "") else "")
         + "On termination, the Tenant shall vacate the premises and hand over possession in the same condition as received, "
           "subject to normal wear and tear."),

        ("Dispute Resolution",
         "Any dispute arising out of or in connection with this agreement shall first be attempted to be resolved "
         "through mutual negotiation. In the absence of resolution, the dispute shall be referred to arbitration "
         "or competent courts having jurisdiction over the property location."),

        ("Governing Law",
         "This agreement shall be governed by the laws of India including the Transfer of Property Act, 1882, "
         "and other applicable local laws and tenancy regulations."),
    ]

    for i, (title, body) in enumerate(clauses, start=1):
        story += _clause(i, title, body, styles)

    # ── Additional / Custom Terms ─────────────────────────────────────────────
    if additional_details and str(additional_details).strip():
        story += _section("6. Additional Details", styles)
        story.append(Paragraph(_p(additional_details), styles["BodyJustified"]))
        story.append(Spacer(1, 3))

    if custom_terms and str(custom_terms).strip().lower() not in ("no", "none", ""):
        story += _section("7. Special / Custom Terms", styles)
        story.append(Paragraph(
            "The following special terms have been mutually agreed between the Landlord and Tenant "
            "and shall form part of this agreement:",
            styles["BodyIndian"]
        ))
        story.append(Spacer(1, 3))
        # Render each line as a separate bullet if multi-line
        for line in str(custom_terms).strip().split("\n"):
            line = line.strip()
            if line:
                story.append(Paragraph(f"• {_p(line)}", styles["BodyIndian"]))
        story.append(Spacer(1, 4))

    # ── Signatures ───────────────────────────────────────────────────────────
    story += _section("Signatures", styles)
    story.append(Paragraph(
        "This agreement is executed on the date mentioned above in the presence of the following witnesses.",
        styles["BodyIndian"]
    ))
    story.append(Spacer(1, 6))

    sig_table = Table(
        [
            [Paragraph("<b>LANDLORD</b>", styles["BodyIndian"]),
             Paragraph("<b>TENANT</b>", styles["BodyIndian"])],
            [Paragraph(f"Name: {_clean(landlord_name)}", styles["BodyIndian"]),
             Paragraph(f"Name: {_clean(tenant_name)}", styles["BodyIndian"])],
            [Paragraph("Signature: ____________________", styles["BodyIndian"]),
             Paragraph("Signature: ____________________", styles["BodyIndian"])],
            [Paragraph(f"Date: {today}", styles["BodyIndian"]),
             Paragraph(f"Date: {today}", styles["BodyIndian"])],
            [Paragraph(f"Place: {_clean(property_address)}", styles["BodyIndian"]),
             Paragraph(f"Place: {_clean(property_address)}", styles["BodyIndian"])],
        ],
        colWidths=[88 * mm, 88 * mm], hAlign="LEFT",
    )
    sig_table.setStyle(TableStyle([
        ("BACKGROUND",   (0, 0), (-1, 0), colors.HexColor("#DCE8F3")),
        ("BOX",          (0, 0), (-1, -1), 0.5, colors.HexColor("#A8C0D8")),
        ("INNERGRID",    (0, 0), (-1, -1), 0.4, colors.HexColor("#A8C0D8")),
        ("VALIGN",       (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING",   (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 6),
        ("LEFTPADDING",  (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(sig_table)
    story.append(Spacer(1, 8))

    # Witness block
    story.append(Paragraph("<b>Witnesses:</b>", styles["BodyIndian"]))
    witness_table = Table(
        [
            [Paragraph("Witness 1", styles["BodyIndian"]),
             Paragraph("Witness 2", styles["BodyIndian"])],
            [Paragraph("Name: ____________________", styles["BodyIndian"]),
             Paragraph("Name: ____________________", styles["BodyIndian"])],
            [Paragraph("Signature: ________________", styles["BodyIndian"]),
             Paragraph("Signature: ________________", styles["BodyIndian"])],
            [Paragraph("Address: _________________", styles["BodyIndian"]),
             Paragraph("Address: _________________", styles["BodyIndian"])],
        ],
        colWidths=[88 * mm, 88 * mm], hAlign="LEFT",
    )
    witness_table.setStyle(TableStyle([
        ("BOX",          (0, 0), (-1, -1), 0.5, colors.HexColor("#BBBBBB")),
        ("INNERGRID",    (0, 0), (-1, -1), 0.4, colors.HexColor("#DDDDDD")),
        ("TOPPADDING",   (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 5),
        ("LEFTPADDING",  (0, 0), (-1, -1), 6),
    ]))
    story.append(witness_table)
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        "Note: This agreement should be executed on stamp paper of appropriate value and registered "
        "at the Sub-Registrar's office as required under local laws.",
        styles["SmallIndian"]
    ))

    return _build_pdf(filename, story)


# ─────────────────────────────────────────────────────────────────────────────
# Affidavit — richer version
# ─────────────────────────────────────────────────────────────────────────────

def generate_affidavit_document(
    name: str,
    issue: str,
    age: str = "",
    occupation: str = "",
    address: str = "",
    id_proof: str = "",
    additional_details: str = "",
    purpose: str = "",
    custom_facts: str = "",
    # Legacy compat
    location: str = "",
):
    address = address or location
    styles  = _styles()
    today   = datetime.now().strftime("%d-%m-%Y")
    filename = f"Affidavit_{_safe_filename(name)}_{datetime.now().strftime('%d%m%Y_%H%M%S')}.pdf"

    story = [
        Paragraph("AFFIDAVIT", styles["DocTitleIndian"]),
        Paragraph(
            "Sworn Statement / Solemn Affirmation — Draft for review before Notary / Oath Commissioner / Executive Magistrate",
            styles["DocSubTitleIndian"]
        ),
        Spacer(1, 6),
    ]

    # ── Deponent Details ─────────────────────────────────────────────────────
    story += _section("Deponent Details", styles)
    story.append(_kv_table([
        ("Full Name",              name),
        ("Age",                    age or "[Age]"),
        ("Occupation",             occupation or "[Occupation]"),
        ("Residential Address",    address),
        ("ID Proof",               id_proof or "[Aadhaar / PAN / Voter ID / Passport Number]"),
        ("Purpose of Affidavit",   purpose or "[Court / Government office / Bank / Other]"),
        ("Date",                   today),
        ("Place",                  address or "[City / Town]"),
    ], styles))
    story.append(Spacer(1, 5))

    # ── Subject ──────────────────────────────────────────────────────────────
    story += _section("Subject Matter", styles)
    story.append(Paragraph(_p(f"<b>RE:</b> {issue}"), styles["BodyIndian"]))
    story.append(Spacer(1, 5))

    # ── Statement ────────────────────────────────────────────────────────────
    story += _section("Statement on Solemn Affirmation", styles)

    opening = (
        f"I, <b>{_p(name)}</b>, aged <b>{age or '[Age]'}</b>, "
        f"son/daughter/spouse of <b>[Father/Husband/Wife Name]</b>, "
        f"occupation: <b>{occupation or '[Occupation]'}</b>, "
        f"residing at <b>{_p(address)}</b>, "
        f"do hereby solemnly affirm and state as under:"
    )
    story.append(Paragraph(opening, styles["BodyJustified"]))
    story.append(Spacer(1, 5))

    base_statements = [
        f"That I am the deponent herein and am fully competent to make this affidavit.",
        f"That the subject matter of this affidavit is: {issue}.",
        f"That the facts stated herein are within my personal knowledge and are true and correct to "
        f"the best of my knowledge, information, and belief.",
        _clean(additional_details, default="[State all facts and circumstances in detail here, chronologically.]"),
        "That no material fact has been concealed or misstated herein.",
        "That I have not filed any other affidavit or sworn statement in any court or before any authority "
        "in respect of the same subject matter, except as stated herein.",
        "That this affidavit is being made for the purpose stated above and for no other purpose.",
    ]

    for idx, stmt in enumerate(base_statements, start=1):
        story.append(Paragraph(f"<b>{idx}.</b> {_p(stmt)}", styles["BodyJustified"]))
        story.append(Spacer(1, 3))

    # Custom facts
    if custom_facts and str(custom_facts).strip().lower() not in ("no", "none", ""):
        story.append(Spacer(1, 2))
        story.append(Paragraph("<b>Additional Statements:</b>", styles["ClauseTitle"]))
        for line in str(custom_facts).strip().split("\n"):
            line = line.strip()
            if line:
                story.append(Paragraph(f"• {_p(line)}", styles["BodyJustified"]))
        story.append(Spacer(1, 4))

    # ── Verification ─────────────────────────────────────────────────────────
    story += _section("Verification", styles)
    verification = (
        f"I, <b>{_p(name)}</b>, the deponent above-named, do hereby verify that the contents "
        f"of this affidavit are true and correct to the best of my knowledge and belief, "
        f"and no part of it is false, and nothing material has been concealed therein. "
        f"Verified at <b>{_p(address or '[Place]')}</b> on <b>{today}</b>."
    )
    story.append(Paragraph(verification, styles["BodyJustified"]))
    story.append(Spacer(1, 8))

    # ── Signature Block ───────────────────────────────────────────────────────
    story.append(Table(
        [
            [Paragraph("<b>Deponent</b>", styles["BodyIndian"]),
             Paragraph("<b>Before Me (Notary / Oath Commissioner)</b>", styles["BodyIndian"])],
            [Paragraph(f"Name: {_clean(name)}", styles["BodyIndian"]),
             Paragraph("Name: _______________________", styles["BodyIndian"])],
            [Paragraph("Signature / Thumb Impression:", styles["BodyIndian"]),
             Paragraph("Signature: ___________________", styles["BodyIndian"])],
            [Paragraph("__________________________", styles["BodyIndian"]),
             Paragraph("Stamp / Registration No.: ____", styles["BodyIndian"])],
            [Paragraph(f"Date: {today}", styles["BodyIndian"]),
             Paragraph(f"Date: {today}", styles["BodyIndian"])],
            [Paragraph(f"Place: {_clean(address)}", styles["BodyIndian"]),
             Paragraph("Place: ______________________", styles["BodyIndian"])],
        ],
        colWidths=[88 * mm, 88 * mm], hAlign="LEFT",
    ))
    story[-1].setStyle(TableStyle([
        ("BACKGROUND",   (0, 0), (-1, 0), colors.HexColor("#DCE8F3")),
        ("BOX",          (0, 0), (-1, -1), 0.5, colors.HexColor("#A8C0D8")),
        ("INNERGRID",    (0, 0), (-1, -1), 0.4, colors.HexColor("#A8C0D8")),
        ("VALIGN",       (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING",   (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 6),
        ("LEFTPADDING",  (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        "Note: This affidavit must be sworn before a Notary Public / Oath Commissioner / Executive Magistrate "
        "to be legally valid. Ensure correct stamp duty is paid as required by State law.",
        styles["SmallIndian"]
    ))

    return _build_pdf(filename, story)


# ─────────────────────────────────────────────────────────────────────────────
# generate_document_from_chat — legacy compat wrapper
# ─────────────────────────────────────────────────────────────────────────────

def generate_document_from_chat(
    chat_text: str,
    document_type: str,
    existing_draft: Dict[str, Any] = None,
    mode: str = "auto",
) -> str:
    document_type = (document_type or "").lower().strip()
    data = extract_document_data_from_chat(chat_text, document_type, existing_draft=existing_draft, mode=mode)

    if document_type == "fir":
        return generate_fir_document(
            name=data.get("name", ""),
            issue=data.get("issue", ""),
            location=data.get("location", ""),
            complainant_name=data.get("complainant_name", "") or data.get("name", ""),
            respondent_name=data.get("respondent_name", ""),
            police_station=data.get("police_station", ""),
            district=data.get("district", ""),
            state=data.get("state", "Uttar Pradesh"),
            incident_date=data.get("incident_date", ""),
            incident_time=data.get("incident_time", ""),
            incident_details=data.get("incident_details", ""),
            witnesses=data.get("witnesses", []),
            annexures=data.get("annexures", []),
            fir_number=data.get("fir_number", ""),
        )

    if document_type in {"notice", "legal_notice"}:
        return generate_legal_notice_document(
            complainant_name=data.get("complainant_name", "") or data.get("name", ""),
            complainant_address=data.get("complainant_address", "") or data.get("location", ""),
            respondent_name=data.get("respondent_name", ""),
            respondent_address=data.get("respondent_address", ""),
            issue=data.get("issue", ""),
            demand=data.get("demand", ""),
            reply_days=int(data.get("reply_days") or 15),
            relationship=data.get("relationship", ""),
            incident_dates=data.get("incident_dates", ""),
            demand_amount=data.get("demand_amount", ""),
            additional_details=data.get("additional_details", ""),
            custom_terms=data.get("custom_terms", ""),
        )

    if document_type == "rental":
        return generate_rental_agreement_document(
            landlord_name=data.get("landlord_name", "") or data.get("name", ""),
            landlord_address=data.get("landlord_address", ""),
            tenant_name=data.get("tenant_name", ""),
            tenant_address=data.get("tenant_address", ""),
            house_no=data.get("house_no", ""),
            property_address=data.get("property_address", "") or data.get("location", ""),
            rent_amount=data.get("rent_amount", ""),
            security_deposit=data.get("security_deposit", ""),
            start_date=data.get("start_date", ""),
            end_date=data.get("end_date", ""),
            notice_period=data.get("notice_period", "1 month"),
            lock_in_period=data.get("lock_in_period", ""),
            maintenance=data.get("maintenance", ""),
            utilities=data.get("utilities", ""),
            additional_details=data.get("additional_details", ""),
            custom_terms=data.get("custom_terms", ""),
        )

    if document_type == "affidavit":
        return generate_affidavit_document(
            name=data.get("name", ""),
            age=data.get("age", ""),
            occupation=data.get("occupation", ""),
            address=data.get("address", "") or data.get("location", ""),
            id_proof=data.get("id_proof", ""),
            issue=data.get("issue", ""),
            additional_details=data.get("additional_details", ""),
            purpose=data.get("purpose", ""),
            custom_facts=data.get("custom_facts", ""),
        )

    raise ValueError(f"Unsupported document type: {document_type}")